// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjizepapbrxjuunzzwek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqaXplcGFwYnJ4anV1bnp6d2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NjE3NTYsImV4cCI6MjA2MzIzNzc1Nn0.JDR7-hzyqwxAsmanDra7gfYOEhwGYBh32Rx5B60yj_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);